version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - mynetwork
    hostname: rabbitmq
    ports:
      - 5672:5672  # Puerto de RabbitMQ para la mensajería
      - 15672:15672 # Puerto de RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  eureka:
    container_name: eureka-server-image
    image: eureka:1.0
    build: ../FileServerDocker/EUREKA/
    ports:
      - 8761:8761
    networks:
      - mynetwork
  FileServerSave:
    container_name: save-service-app
    image: file_server-save:1.0
    build: ../FileServerDocker/SaveFile/
    depends_on:
      - eureka
      - rabbitmq
    environment:
      POSTGRES_DB: archivedb
      POSTGRES_USER: ema
      POSTGRES_PASSWORD: 123
      FILE_STORAGE_PATH: /mnt/shared/files/
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      EUREKA_SERVER_URL: http://eureka-server-image:8761/eureka # URL de Eureka
    volumes:
      - shared_files:/mnt/shared/files
    networks:
      - mynetwork
  FileServerGet:
    container_name: get-service-app
    image: file_server-get:1.0
    build: ../FileServerDocker/GetFile/
    depends_on:
      - eureka
      - rabbitmq
    environment:
      POSTGRES_DB: archivedb
      POSTGRES_USER: ema
      POSTGRES_PASSWORD: 123
      FILE_STORAGE_PATH: /mnt/shared/files/
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      EUREKA_SERVER_URL: http://eureka-server-image:8761/eureka # URL de Eureka
    volumes:
      - shared_files:/mnt/shared/files
    networks:
      - mynetwork
  api-gateway:
    container_name: api-gateway-app
    image: api-gateway:1.0
    build: ../FileServerDocker/ApiGateway/
    depends_on:
      - eureka
      - FileServerSave
      - FileServerGet
    environment:
      EUREKA_SERVER_URL: http://eureka-server-image:8761/eureka # URL de Eureka
    ports:
      - 8080:8080  # Exponer solo el API Gateway al host
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  shared_files:
    driver: local