global:
  scrape_interval: 15s  # Intervalo de tiempo para recolectar métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eureka'
    eureka_sd_configs:
      - server: 'http://eureka-server-image:8761/eureka'

    relabel_configs:
      # Scrape solo servicios con "prometheus.scrape = true" en los metadatos
      - source_labels: [__meta_eureka_app_instance_metadata_prometheus_scrape]
        action: keep
        regex: true

      # Usar el path personalizado para las métricas basado en "prometheus.path"
      - source_labels: [__meta_eureka_app_instance_metadata_prometheus_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

      # Scrape solo en el puerto definido en "prometheus.port"
      - source_labels: [__address__, __meta_eureka_app_instance_metadata_prometheus_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']  # Puerto donde está expuesto RabbitMQ Exporter