app:
  name: SaveFile
  desc: FileServer save file
  version: 1.0.0
  url: http://localhost:8080
  dev-name: Ema Beltramo
  dev-email: beltramoemanuel@gmail.com
  file-storage-path: ${FILE_STORAGE_PATH:/shared/files/}

spring:
  application:
    name: SaveFile
  datasource:
    url: jdbc:postgresql://localhost:5432/fileserverdb
    username: ema
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /docs
    enabled: true
  packages-to-scan: FileServer.SaveFile.controller
  show-actuator: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs-ui
    enabled: true